import "./globals.css";
import SupabaseProvider from "./providers/SupabaseProvider";

export const metadata = {
  title: "AI Quiz Generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SupabaseProvider>{children}</SupabaseProvider>
      </body>
    </html>
  );
}
